(cl:in-package msg_gnss_prep-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          BODY_ACCELERATION_X-VAL
          BODY_ACCELERATION_X
          BODY_ACCELERATION_Y-VAL
          BODY_ACCELERATION_Y
          BODY_ACCELERATION_Z-VAL
          BODY_ACCELERATION_Z
          RAW_ACCELERATION_X-VAL
          RAW_ACCELERATION_X
          RAW_ACCELERATION_Y-VAL
          RAW_ACCELERATION_Y
          RAW_ACCELERATION_Z-VAL
          RAW_ACCELERATION_Z
          RAW_ANGULAR_VELOCITY_X-VAL
          RAW_ANGULAR_VELOCITY_X
          RAW_ANGULAR_VELOCITY_Y-VAL
          RAW_ANGULAR_VELOCITY_Y
          RAW_ANGULAR_VELOCITY_Z-VAL
          RAW_ANGULAR_VELOCITY_Z
          BODY_VELOCITY_X-VAL
          BODY_VELOCITY_X
          BODY_VELOCITY_Y-VAL
          BODY_VELOCITY_Y
          BODY_VELOCITY_Z-VAL
          BODY_VELOCITY_Z
          ORIENTATION_X-VAL
          ORIENTATION_X
          ORIENTATION_Y-VAL
          ORIENTATION_Y
          ORIENTATION_Z-VAL
          ORIENTATION_Z
          ORIENTATION_W-VAL
          ORIENTATION_W
          ROLL_ANGLE-VAL
          ROLL_ANGLE
          PITCH_ANGLE-VAL
          PITCH_ANGLE
          YAW_ANGLE-VAL
          YAW_ANGLE
          FLAG-VAL
          FLAG
          GPS_STATUS-VAL
          GPS_STATUS
))